// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: optimizer_priority.proto

#include "optimizer_priority.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
namespace ge {
namespace optimizers {
class PriorityDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<Priority> _instance;
} _Priority_default_instance_;
}  // namespace optimizers
}  // namespace ge
static void InitDefaultsscc_info_Priority_optimizer_5fpriority_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::ge::optimizers::_Priority_default_instance_;
    new (ptr) ::ge::optimizers::Priority();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::ge::optimizers::Priority::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_Priority_optimizer_5fpriority_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_Priority_optimizer_5fpriority_2eproto}, {}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_optimizer_5fpriority_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_optimizer_5fpriority_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_optimizer_5fpriority_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_optimizer_5fpriority_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::ge::optimizers::Priority, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::ge::optimizers::Priority, optimizer_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::ge::optimizers::Priority)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::ge::optimizers::_Priority_default_instance_),
};

const char descriptor_table_protodef_optimizer_5fpriority_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\030optimizer_priority.proto\022\rge.optimizer"
  "s\"\035\n\010Priority\022\021\n\toptimizer\030\001 \003(\tb\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_optimizer_5fpriority_2eproto_deps[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_optimizer_5fpriority_2eproto_sccs[1] = {
  &scc_info_Priority_optimizer_5fpriority_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_optimizer_5fpriority_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_optimizer_5fpriority_2eproto = {
  false, false, descriptor_table_protodef_optimizer_5fpriority_2eproto, "optimizer_priority.proto", 80,
  &descriptor_table_optimizer_5fpriority_2eproto_once, descriptor_table_optimizer_5fpriority_2eproto_sccs, descriptor_table_optimizer_5fpriority_2eproto_deps, 1, 0,
  schemas, file_default_instances, TableStruct_optimizer_5fpriority_2eproto::offsets,
  file_level_metadata_optimizer_5fpriority_2eproto, 1, file_level_enum_descriptors_optimizer_5fpriority_2eproto, file_level_service_descriptors_optimizer_5fpriority_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_optimizer_5fpriority_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_optimizer_5fpriority_2eproto)), true);
namespace ge {
namespace optimizers {

// ===================================================================

void Priority::InitAsDefaultInstance() {
}
class Priority::_Internal {
 public:
};

Priority::Priority(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena),
  optimizer_(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:ge.optimizers.Priority)
}
Priority::Priority(const Priority& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      optimizer_(from.optimizer_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:ge.optimizers.Priority)
}

void Priority::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_Priority_optimizer_5fpriority_2eproto.base);
}

Priority::~Priority() {
  // @@protoc_insertion_point(destructor:ge.optimizers.Priority)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void Priority::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void Priority::ArenaDtor(void* object) {
  Priority* _this = reinterpret_cast< Priority* >(object);
  (void)_this;
}
void Priority::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void Priority::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const Priority& Priority::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_Priority_optimizer_5fpriority_2eproto.base);
  return *internal_default_instance();
}


void Priority::Clear() {
// @@protoc_insertion_point(message_clear_start:ge.optimizers.Priority)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  optimizer_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Priority::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // repeated string optimizer = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            auto str = _internal_add_optimizer();
            ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
            CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "ge.optimizers.Priority.optimizer"));
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* Priority::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ge.optimizers.Priority)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated string optimizer = 1;
  for (int i = 0, n = this->_internal_optimizer_size(); i < n; i++) {
    const auto& s = this->_internal_optimizer(i);
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      s.data(), static_cast<int>(s.length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "ge.optimizers.Priority.optimizer");
    target = stream->WriteString(1, s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ge.optimizers.Priority)
  return target;
}

size_t Priority::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ge.optimizers.Priority)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated string optimizer = 1;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(optimizer_.size());
  for (int i = 0, n = optimizer_.size(); i < n; i++) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
      optimizer_.Get(i));
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Priority::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:ge.optimizers.Priority)
  GOOGLE_DCHECK_NE(&from, this);
  const Priority* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<Priority>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:ge.optimizers.Priority)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:ge.optimizers.Priority)
    MergeFrom(*source);
  }
}

void Priority::MergeFrom(const Priority& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:ge.optimizers.Priority)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  optimizer_.MergeFrom(from.optimizer_);
}

void Priority::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:ge.optimizers.Priority)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Priority::CopyFrom(const Priority& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ge.optimizers.Priority)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Priority::IsInitialized() const {
  return true;
}

void Priority::InternalSwap(Priority* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  optimizer_.InternalSwap(&other->optimizer_);
}

::PROTOBUF_NAMESPACE_ID::Metadata Priority::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace optimizers
}  // namespace ge
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::ge::optimizers::Priority* Arena::CreateMaybeMessage< ::ge::optimizers::Priority >(Arena* arena) {
  return Arena::CreateMessageInternal< ::ge::optimizers::Priority >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
